import { type NextPage } from "next";
import Head from "next/head";
import LogComponent from "../components/logcomponent";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SignIn-Up Component</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        <LogComponent />
      </main>
    </>
  );
};

export default Home;
