import { type NextPage } from "next";
import Head from "next/head";
import LogComponent from "../components/logcomponent";
import { BsSunFill, BsMoonFill } from "react-icons/bs";
import { useAtom } from "jotai";
import { colorThemeAtom } from "../jotai/atoms";
const Home: NextPage = () => {
  const [theme, setTheme] = useAtom(colorThemeAtom);
  return (
    <>
      <Head>
        <title>SignIn-Up Component</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex min-h-screen flex-col items-center justify-center bg-white">
        <div
          className={`absolute top-4 left-4 z-50 cursor-pointer rounded-full ${
            theme === "dark" ? "bg-[#150050]" : "bg-[#e63946]"
          } p-2 text-white transition-all duration-300 hover:scale-125`}
        >
          {theme === "dark" ? (
            <BsSunFill onClick={() => setTheme("light")} />
          ) : (
            <BsMoonFill onClick={() => setTheme("dark")} />
          )}
        </div>

        <LogComponent />
      </main>
    </>
  );
};

export default Home;
